apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-app-ingress
  namespace: kubectl
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing       # or internal for private ALB
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/rewrite-target: /$1            # URL Rewrite rule
    alb.ingress.kubernetes.io/ssl-redirect: "false"          # Set to true if you want HTTPS
    alb.ingress.kubernetes.io/healthcheck-path: /health      # Health check path (optional)
spec:
  ingressClassName: alb  # Specifies to use the AWS ALB Ingress Controller
  rules:
    - http:
        paths:
          - path: /?(.*)  # Frontend path
            pathType: Prefix
            backend:
              service:
                name: mern-app-service
                port:
                  number: 3000

          - path: /api/?(.*)  # Backend API path
            pathType: Prefix
            backend:
              service:
                name: mern-app-service
                port:
                  number: 5000
